name: medical_ocr_app
description: Mobile Flutter client for the OCR + BioBERT pipeline backend.
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
